### ISSUE TITLE
Could you share your PDSN code？

### ISSUE THREAD

**Issue by fanfan1998** [haoosz/FFR-Net#2]

**Comment by haoosz** [comment]
Please see this work [PDSN](https://github.com/linserSnow/PDSN).

**Comment by fanfan1998** [comment]
Hello, what are casia_cleanlist.txt and lfw_pairs.txt in dataloader.py? Can you share them with me? What kind of preprocessing should the datasets CASIA and LFW undergo? The models.net_sphere in lfw_eval.py also seem to be missing.   Thanks for your answer!

**Comment by haoosz** [comment]
1. The download links of datasets and txt files have been added in README. Please check it.
2. The preprocessing is face alignment and cropping (with ground-truth face landmarks). The data shared in this repo has been preprocessed beforehand and you can directly load it.
3. `models.net_sphere` is an old model just for debugging. You don't need to run lfw_eval.py and you can just ignore it.

Hope the above is helpful to you. Thanks.
